# Site settings
name: Uta's Blog
email: lijun.kawasaki@gmail.com
author: lijun
url: https://utanesuke0612.github.io/
#resume_site: http://www.hifreud.com/Resume.io/
github: https://github.com/utanesuke0612/
baseurl: ""
description: Actually, less is more!
meta_description: 个人博客;学而不思则罔;思而不学则殆;生命不止;折腾不休
motto: Haste makes waste.
banner: 学而不思则罔，思而不学则殆。

#permalink: /:categories/:year/:month/:day/:title/
permalink: /:year/:month/:day/:title/
paginate: 10

exclude: ['README.md', 'Gemfile.lock', 'Gemfile', 'Rakefile']

github_username: utanesuke0612
highlighter: Pygments

# Build settings
markdown: kramdown

#baidu_analysis: 94be4b0f9fc5d94cc0d0415ea6761ae9
